completion.use_best_match: true
prompt.filebrowser: true
session.lazy_restore: true
#spellcheck.languages: ["de-DE", "en-US"]
content.proxy: system

aliases:
    q: quit
    w: session-save
    wq: quit --save
    burp: set content.proxy http://127.0.0.1:8080/
    noburp: set content.proxy system
