#!/bin/sh
set -e
if ! command -v ctags >/dev/null 2>&1
then
    printf "Sorry, ctags was not found in \$PATH\n" >&2
    exit 1
fi

dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | ctags --tag-relative=yes -L - -f "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
